### ISSUE TITLE
Make it a real "app"

### ISSUE THREAD

**Issue by cdvv7788** [arjunkomath/Simple-Q-A-App-using-Python-Django#4]
Cuurrently the "app" is a django project. It would be nice to make it easier to install, remove some name clashes and make it reusable. That would require a lot of refactoring but i think that the base is there.
I could help with the refactoring if you want, but add a license file to the repository first.

**Comment by arjunkomath** [comment]
@cdvv7788 What you have suggested is good, but unfortunately, I'm not actively maintaining this repo anymore. It was a project done long back, anyway I'll add the license file.
