### ISSUE TITLE
Version 0.10.12?

### ISSUE THREAD

**Issue by colin-byrne-1** [arjunkomath/Simple-Q-A-App-using-Python-Django#6]
Version 0.10.12 is referenced in the readme (python 3.5+, django 2.0) but not available in python repository... Where are we supposed to get this? It's hard to tell if the the code is even ahead of 0.10.0... if it is, I suppose I could just fork it...

**Comment by arjunkomath** [comment]
@cobyrne09 This repo is no longer maintained. Please report the issue in this fork https://github.com/swappsco/django-qa
